KodyPay/kody-clientsdk-php

- samples/php7/composer.json
- samples/php7/src/get_list_of_terminals.php
- samples/php8/ecom-server/composer.json
- samples/php8/ecom-server/docker-compose.yml
- samples/php8/ecom-server/public/checkout.php
- samples/php8/ecom-server/public/checkout_payment.php
- samples/php8/ecom-server/public/config.php
- samples/php8/pos/composer.json
Added `show_timer` and `expiring_seconds` fields  to reflect the latest changes in wombat.
- Added checkbox to hide/show expiration fields. If checkbox is NOT selected, the expiration object will not be set
- `expiring_seconds` field is restricted to positive numbers only
- Used a dropdown since `show_timer` value will be either true or empty
> Added show_timer and expiring_seconds fields

- samples/php8/ecom-server/public/checkout.php
Updated README to reflect the latest field additions
> Updated README

- samples/php8/ecom-server/public/terminal_payment_status_check.php
Show `totalAmount`, `saleAmount` and `tipsAmount`  from the PayResponse
> PBBV0-70 - Include amounts in the response

- samples/php7/composer.json
- samples/php8/ecom-server/composer.json
- samples/php8/pos/composer.json
Reverts KodyPay/kody-clientsdk-php#14
> Revert "Update composer files"

- samples/php7/composer.json
- samples/php8/ecom-server/composer.json
- samples/php8/ecom-server/public/terminal_payment_form.php
- samples/php8/ecom-server/public/terminal_submit_payment.php
As part of PP-927: Include QR payment fields and functionality
> PP-927 as a user i want to pay using the terminal with ali pay and we chat

- samples/php8/ecom-server/public/terminal_payment_form.php
- samples/php8/ecom-server/public/terminal_submit_payment.php
- Activate QR code scanner added
> Include activate_qr_code_scanner

- samples/php8/ecom-server/Dockerfile
- Removed the installation of grpc from source code that is redundant with `pecl install grpc`
> Fix docker image

- samples/php8/ecom-server/public/transactions.php
Fix broken page https://ecom-php-demo.kody.com/transactions.php
> fix: fix pagecursor

- samples/php8/ecom-server/public/functions.php
- samples/php8/ecom-server/public/refund-form.php
- samples/php8/ecom-server/public/transactions.php
- Add the Payment Details which includes the amount of transactions
- Breakdown into sections for better UI
> Bam 141 add amount

- samples/php8/ecom-server/public/terminal_payment_form.php
- samples/php8/ecom-server/public/terminal_submit_payment.php
- remove hidden payment method
- add comment on how to multiple select accepts only
> upt: remove hidden payment method

- samples/php8/ecom-server/public/terminal_payment_form.php
> fix: make CARD as default

- samples/php8/ecom-server/public/refund-form.php
> upt: fix error messeage; add return links

- samples/php8/ecom-server/public/checkout_return.php
- samples/php8/ecom-server/public/config.php
- samples/php8/ecom-server/public/index.php
- samples/php8/ecom-server/public/terminals.php
- Added form with inputs for Store ID and API Key configuration
- Implemented cookie storage for user settings (1-hour expiration)
- Added Save and Reset buttons with JavaScript handlers
- Created status messaging system for operation feedback
- Added input validation to ensure both fields have values
> upt: add settings part

- samples/php8/ecom-server/public/checkout_return.php
- samples/php8/ecom-server/public/terminal_submit_payment.php
- use fetch
- add retry
- add error handling
> upt: add retry and error handling

- samples/php8/ecom-server/nginx.conf
> chore: extend timeout

- README.md
> upt: clean up readme

- samples/php8/ecom-server/public/config.php
use default if the env is not set
> upt: use default if the env is not set

- samples/php8/ecom-server/public/checkout.php
> upt: update label

- samples/php8/ecom-server/public/checkout_return.php
> upt: show list all transactions link

- samples/php8/ecom-server/public/api/payments.php
- samples/php8/ecom-server/public/transactions.php
> upt: show paid_amount

- samples/php8/ecom-server/public/checkout.php
- samples/php8/ecom-server/public/js/bubble.php
- samples/php8/ecom-server/public/terminal_payment_form.php
- samples/php8/ecom-server/public/terminal_submit_payment.php
- samples/php8/ecom-server/public/terminals.php
- samples/php8/ecom-server/public/transactions.php
> upt: add doc bubble

- README.md
- samples/php8/ecom-server/public/checkout_return.php
- samples/php8/ecom-server/public/js/bubble.php
- samples/php8/ecom-server/public/refund-form.php
- Updated installation guide
- Updated the docs bubble
> upt: update installation guide

- README.md
- samples/php8/ecom-server/composer.json
- samples/php8/ecom-server/public/checkout.php
- samples/php8/ecom-server/public/checkout_payment.php
https://kodypay.atlassian.net/browse/BAM-430
* updates the grpc client package
* adds an 'enable pay by bank' checkbox to the checkout form of the demo client (API not yet implemented)
> BAM-430: Enable pay by bank in the ecom demo app

- samples/php8/ecom-server/public/api/delete-card-token.php
- samples/php8/ecom-server/public/api/pay-with-card-token.php
- samples/php8/ecom-server/public/css/sdk-common.php
- samples/php8/ecom-server/public/token-payment-tokens.php
• Refactored duplicate tab switching functions into generic showSectionTab()
• Added collapsible accordion sections with navigation bar
• Fixed API endpoint reference from pay-with-token.php to pay-with-card-token.php
• Improved visual design with gradients, animations, and responsive layout
> upt: add delete token and pay with card token
